id: P723C293B
initial_creation_type: input
source_metadata:
  title: Āṅgirasasmṛti
  language:
  - English
  - Sanskrit
  term: Sanskrit -- Śāstra -- Dharma -- Smṛti
  data entry: Oliver Hellwig
  contribution to GRETIL: Oliver Hellwig
  initial normalization and conversion to legacy GRETIL formats: Reinhold Grünendahl
  normalization and conversion to TEI-conformant markup: Maximilian Mehner
created_at: '2022-03-09T15:28:08.807185'
last_modified_at: '2022-03-09T15:28:08.807199'
